on: 
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - run: yarn install
      - run: yarn build
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              get.sh
              ./dist/mohaya
